In [15]:



import pandas as pd

In [16]:
df=pd.read_csv("shopping_customer_data.csv")

In [17]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,22,Female,Bag,Footwear,484,Delhi,XL,Red,Summer,2.6,No,Express,No,Yes,5,Net Banking,Weekly
1,2,58,Female,Shirt,Footwear,105,Lucknow,M,White,Summer,1.5,Yes,Express,Yes,Yes,17,Net Banking,Monthly
2,3,52,Female,Watch,Footwear,324,Lucknow,L,Blue,Autumn,2.5,Yes,Next Day,No,No,13,Net Banking,Weekly
3,4,40,Male,Jeans,Footwear,404,Lucknow,XL,Blue,Spring,2.6,Yes,Next Day,Yes,No,24,Card,Quarterly
4,5,40,Female,Watch,Clothing,441,Mumbai,XL,Black,Winter,1.4,No,Express,No,No,15,Card,Quarterly

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [19]:
df.describe(include=
           'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,5,3,NaN,4,4,4,4,NaN,2,3,2,2,NaN,4,3
top,NaN,NaN,Male,Watch,Accessories,NaN,Lucknow,S,White,Autumn,NaN,Yes,Standard,Yes,Yes,NaN,Card,Weekly
freq,NaN,NaN,1986,806,1352,NaN,981,1018,1026,995,NaN,1978,1322,1975,1958,NaN,1021,1327
mean,1950.500000,43.522051,NaN,NaN,NaN,253.020513,NaN,NaN,NaN,NaN,3.033963,NaN,NaN,NaN,NaN,24.876667,NaN,NaN
std,1125.977353,15.009453,NaN,NaN,NaN,142.625920,NaN,NaN,NaN,NaN,1.164091,NaN,NaN,NaN,NaN,14.488028,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,975.750000,30.000000,NaN,NaN,NaN,128.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,12.000000,NaN,NaN
50%,1950.500000,43.000000,NaN,NaN,NaN,253.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,375.000000,NaN,NaN,NaN,NaN,4.100000,NaN,NaN,NaN,NaN,37.000000,NaN,NaN
max,3900.000000,69.000000,NaN,NaN,NaN,499.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,49.000000,NaN,NaN

In [20]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [21]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [22]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [23]:

df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [24]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [25]:
type(df)

pandas.core.frame.DataFrame

In [26]:
labels=['young_adult','adult','middle_age','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [9]:
df[['age','age_group']].head(5)

NameError: name 'df' is not defined

In [10]:
# Create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

NameError: name 'df' is not defined

In [11]:
df[['purchase_frequency_days','frequency_of_purchases']].head(15)

NameError: name 'df' is not defined

In [12]:
(df['promo_code_used']==df['discount_applied']).all()

NameError: name 'df' is not defined

In [13]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\vs\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\vs\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\vs\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\vs\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [14]:
from sqlalchemy import create_engine

username = "postgres"
password = "newpassword123"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

table_name = "customer"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(
    f"Data successfully loaded into table '{table_name}' in database '{database}'."
)

NameError: name 'df' is not defined

In [ ]:
from sqlalchemy import create_engine

username = "postgres"
password = "newpassword123"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

table_name = "customer"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(
    f"Data successfully loaded into table '{table_name}' in database '{database}'."
)